import type {
  TeacherFormSignatureRow,
  TeacherParentForm,
} from "./types";

export const MOCK_TEACHER_PARENT_FORMS: TeacherParentForm[] = [
  {
    id: "form-trampoline-waiver",
    title: "Trampoline liability waiver",
    description:
      "Required before students participate in trampoline activities during PE.",
    formType: "upload",
    status: "active",
    classroomIds: ["classroom-butterflies", "classroom-sunflowers"],
    classroomNames: ["Butterflies", "Sunflowers"],
    dueDate: "2026-03-28",
    requireSignature: true,
    uploadFormat: "pdf",
    uploadFileName: "trampoline-liability-waiver.pdf",
    uploadFileSize: "245 KB",
    totalFamilies: 12,
    signedFamilies: 8,
    createdAt: "2026-03-01T10:00:00.000Z",
    updatedAt: "2026-03-10T14:30:00.000Z",
  },
  {
    id: "form-field-trip",
    title: "Spring field trip permission",
    description:
      "Permission slip for the April 12 visit to the nature center.",
    formType: "builder",
    status: "active",
    classroomIds: ["classroom-butterflies"],
    classroomNames: ["Butterflies"],
    dueDate: "2026-04-05",
    requireSignature: true,
    fields: [
      {
        id: "f1",
        type: "short_text",
        label: "Emergency contact name",
        required: true,
      },
      {
        id: "f2",
        type: "short_text",
        label: "Emergency contact phone",
        required: true,
      },
      {
        id: "f3",
        type: "checkbox",
        label: "I give permission for my child to attend the field trip",
        required: true,
      },
      {
        id: "f4",
        type: "signature",
        label: "Parent / guardian signature",
        required: true,
        locked: true,
      },
    ],
    totalFamilies: 12,
    signedFamilies: 5,
    createdAt: "2026-03-05T09:00:00.000Z",
    updatedAt: "2026-03-12T11:00:00.000Z",
  },
  {
    id: "form-photo-release",
    title: "Photo release",
    description: "Allow the school to use photos of your child in newsletters.",
    formType: "upload",
    status: "draft",
    classroomIds: ["classroom-sunflowers"],
    classroomNames: ["Sunflowers"],
    dueDate: null,
    requireSignature: true,
    uploadFormat: "pdf",
    uploadFileName: "photo-release-2026.pdf",
    uploadFileSize: "180 KB",
    totalFamilies: 10,
    signedFamilies: 0,
    createdAt: "2026-03-14T16:00:00.000Z",
    updatedAt: "2026-03-14T16:00:00.000Z",
  },
  {
    id: "form-summer-camp",
    title: "Summer camp addendum",
    description: "Additional terms for optional summer camp enrollment.",
    formType: "upload",
    status: "archived",
    classroomIds: ["classroom-butterflies", "classroom-sunflowers"],
    classroomNames: ["Butterflies", "Sunflowers"],
    dueDate: "2025-06-01",
    requireSignature: true,
    uploadFormat: "docx",
    uploadFileName: "summer-camp-addendum.docx",
    uploadFileSize: "92 KB",
    totalFamilies: 22,
    signedFamilies: 22,
    createdAt: "2025-05-01T08:00:00.000Z",
    updatedAt: "2025-06-15T10:00:00.000Z",
  },
];

export const MOCK_FORM_SIGNATURE_ROWS: Record<string, TeacherFormSignatureRow[]> = {
  "form-trampoline-waiver": [
    {
      id: "sig-1",
      formId: "form-trampoline-waiver",
      familyName: "Chen family",
      studentNames: ["Maya Chen"],
      status: "signed",
      signedAt: "2026-03-08",
    },
    {
      id: "sig-2",
      formId: "form-trampoline-waiver",
      familyName: "Torres family",
      studentNames: ["Liam Torres"],
      status: "signed",
      signedAt: "2026-03-09",
    },
    {
      id: "sig-3",
      formId: "form-trampoline-waiver",
      familyName: "Patel family",
      studentNames: ["Sofia Patel"],
      status: "pending",
      signedAt: null,
    },
    {
      id: "sig-4",
      formId: "form-trampoline-waiver",
      familyName: "Adkins family",
      studentNames: ["Noah Adkins"],
      status: "overdue",
      signedAt: null,
    },
    {
      id: "sig-5",
      formId: "form-trampoline-waiver",
      familyName: "Kim family",
      studentNames: ["Zoe Kim"],
      status: "signed",
      signedAt: "2026-03-10",
    },
    {
      id: "sig-6",
      formId: "form-trampoline-waiver",
      familyName: "Brooks family",
      studentNames: ["Ethan Brooks"],
      status: "pending",
      signedAt: null,
    },
  ],
  "form-field-trip": [
    {
      id: "sig-ft-1",
      formId: "form-field-trip",
      familyName: "Chen family",
      studentNames: ["Maya Chen"],
      status: "signed",
      signedAt: "2026-03-11",
    },
    {
      id: "sig-ft-2",
      formId: "form-field-trip",
      familyName: "Nguyen family",
      studentNames: ["Isla Nguyen"],
      status: "signed",
      signedAt: "2026-03-12",
    },
    {
      id: "sig-ft-3",
      formId: "form-field-trip",
      familyName: "Hayes family",
      studentNames: ["Oliver Hayes"],
      status: "pending",
      signedAt: null,
    },
  ],
  "form-photo-release": [],
  "form-summer-camp": [
    {
      id: "sig-sc-1",
      formId: "form-summer-camp",
      familyName: "Chen family",
      studentNames: ["Maya Chen"],
      status: "signed",
      signedAt: "2025-05-20",
    },
  ],
};
