import type { ParentThemeTokens } from "@/lib/organization-settings/parent-theme";

/** Marketing site palette from `src/app/globals.css` — for get-started story layout. */
export const MUDKITCHEN_MARKETING_STORY_THEME: ParentThemeTokens = {
  paper: "#F7F1E7",
  ink: "#2B241D",
  muted: "#6D6257",
  line: "#DDD0BE",
  cream: "#F0E6D8",
  white: "#FFFAF4",
  primary: "#2E4A3C",
  primaryDark: "#233B2F",
  primaryLight: "#C5D5B8",
  primarySoft: "color-mix(in srgb, #2E4A3C 12%, transparent)",
  sage: "#A6B89A",
  sky: "#8EBDCB",
  sun: "#EFC56E",
  coral: "#A05C45",
  berry: "#A9667C",
  success: "#4a7c59",
  successBg: "#EDF4EA",
  warning: "#986F14",
  warningBg: "#FFF4D9",
  alert: "#A05C45",
  alertBg: "#FBEDEB",
  info: "#2E4A3C",
  infoBg: "#C5D5B8",
  shadowCard: "0 3px 10px rgba(43, 36, 29, 0.06)",
  shadowPill: "0 2px 8px rgba(43, 36, 29, 0.05)",
  radiusCard: "22px",
  radiusButton: "12px",
  fontDisplay: "var(--font-display)",
  fontBody: "var(--font-secondary)",
};
