-- 2026-08-14: Import Texas microschools from texas_microschools.csv (52 new rows)
-- Skips 11 schools already in public.schools:
--   Acton Academy Northwest Austin, Acton Academy Houston Heights, AHB Community School,
--   Athena Micro-Academy of Austin, Nature's Schoolhouse Microschool, Mirus Academy,
--   Apogee Dripping Springs, ESTEAM Academy, The Woodlands Microschool LLC,
--   Spyrja Academy, Brighter Futures Microschool
-- Idempotent: ON CONFLICT (school_id) DO NOTHING

insert into public.schools (
  school_id,
  name,
  state,
  location,
  website,
  school_model,
  grades,
  estimated_size,
  tuition_schedule,
  strengths,
  pain_points,
  software_fit_reason,
  priority_score,
  confidence,
  is_closing,
  source_file,
  crm_status,
  contact_name,
  contact_email,
  contact_phone
) values

  ('acton-academy-austin-main-campus', 'Acton Academy Austin Main Campus', 'TX', 'Austin', 'https://austin.actonacademy.org', 'Learner-Driven (Acton)', 'K-12', '~60-100 (network)', '$14,894/yr', ARRAY['Strong brand, established Acton network, learner-driven pedagogy well marketed on site']::text[], ARRAY['Manual enrollment/application flows typical of Acton sites; no visible integrated tuition/billing or SIS tool']::text[], 'Needs SaaS to unify applications, tuition billing, and parent portal across multi-age Acton studios', 4, 'Medium', false, 'texas', 'not_contacted', '', '', ''),
  ('acton-academy-bee-cave', 'Acton Academy Bee Cave', 'TX', 'Bee Cave', 'https://beecave.actonacademy.org', 'Learner-Driven (Acton)', 'PreK-12', '~40-60', 'Not published', ARRAY['Part of trusted Acton network, PreK-12 continuity']::text[], ARRAY['No visible tuition/enrollment automation; relies on generic web forms']::text[], 'Multi-age PreK-12 site would benefit from FieldBook''s tuition schedule + application tracking', 3, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('ascent-an-acton-academy', 'Ascent: An Acton Academy', 'TX', 'Austin', 'https://ascent.actonacademy.org', 'Learner-Driven (Acton)', 'PreK-12', '~40-60', 'Not published', ARRAY['Full PreK-12 span, self-directed model']::text[], ARRAY['Complex multi-age operations without visible SIS']::text[], 'High operational complexity fits FieldBook''s multi-age scheduling/tuition tools', 3, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('acton-academy-dripping-springs', 'Acton Academy Dripping Springs', 'TX', 'Dripping Springs', 'https://drippingsprings.actonacademy.org', 'Learner-Driven (Acton)', 'PreK-12', '~40-60', 'Not published', ARRAY['Rural/outdoor-adjacent community, established brand']::text[], ARRAY['No e-commerce/billing visible on site']::text[], 'Outdoor-adjacent Acton studio aligns with Sage Field''s own model; good reference customer', 3, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('acton-academy-fort-worth', 'Acton Academy Fort Worth', 'TX', 'Fort Worth', 'https://fortworth.actonacademy.org', 'Learner-Driven (Acton)', 'K-5', '~30-40', 'Not published', ARRAY['Clear grade band, established network support']::text[], ARRAY['Site lacks integrated application/tuition system']::text[], 'Growing K-5 studio needs streamlined enrollment/applications', 3, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('acton-academy-amarillo', 'Acton Academy Amarillo', 'TX', 'Amarillo', 'https://amarillo.actonacademy.org', 'Learner-Driven (Acton)', 'PreK-12', '~30-50', 'Not published', ARRAY['Serves an underserved West TX market']::text[], ARRAY['Rural market likely lean staff, manual processes']::text[], 'Lean staff = strong candidate for all-in-one ops SaaS', 3, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('acton-academy-beaumont', 'Acton Academy Beaumont', 'TX', 'Beaumont', 'https://beaumont.actonacademy.org', 'Learner-Driven (Acton)', 'PreK-12', '~20-40', 'Not published', ARRAY['Community-based learner-driven model']::text[], ARRAY['Small market, limited marketing tech']::text[], 'Needs affordable website + enrollment tooling for small team', 3, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('acton-academy-corpus-christi', 'Acton Academy Corpus Christi', 'TX', 'Corpus Christi', 'https://corpuschristi.actonacademy.org', 'Learner-Driven (Acton)', 'PreK-12', '~20-40', 'Not published', ARRAY['Coastal community reach, Acton brand trust']::text[], ARRAY['Manual admin processes typical of small Acton studios']::text[], 'Fits FieldBook''s target profile: small team, manual ops', 3, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('acton-academy-cy-fair', 'Acton Academy Cy-Fair', 'TX', 'Cypress', 'https://cyfair.actonacademy.org', 'Learner-Driven (Acton)', 'PreK-12', '~30-50', 'Not published', ARRAY['Growing Houston-suburb presence']::text[], ARRAY['No visible billing/SIS integration']::text[], 'Suburban growth market good for scaling with SaaS', 3, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('acton-academy-mckinney', 'Acton Academy McKinney', 'TX', 'McKinney', 'https://mckinney.actonacademy.org', 'Learner-Driven (Acton)', 'PreK-12', '~30-50', 'Not published', ARRAY['Established in growing DFW suburb']::text[], ARRAY['Manual processes likely as with other Acton studios']::text[], 'DFW growth market, good expansion target', 3, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('acton-leadership-academy-champions-klein', 'Acton Leadership Academy Champions/Klein', 'TX', 'Houston', '', 'Learner-Driven (Acton)', 'Not specified', 'Unknown', 'Not published', ARRAY['Part of Acton network']::text[], ARRAY['Unclaimed directory listing, minimal web presence']::text[], 'Weak digital presence = needs full website + ops platform', 4, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('elite-flexi-school', 'Elite Flexi School', 'TX', 'Austin', '', 'Microschool (Christian)', '1-12', 'Small', 'Not published', ARRAY['Flexible, faith-integrated model serving wide grade range']::text[], ARRAY['Wide grade span (1-12) with one program likely strains manual admin']::text[], 'Wide-span faith school needs unified student/family management', 3, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('long-view-micro-school', 'Long-View Micro School', 'TX', 'Austin', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Member of National Microschooling Center network']::text[], ARRAY['Minimal public info suggests limited web/marketing infrastructure']::text[], 'Needs a modern website + enrollment presence', 3, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('school-on-the-rise', 'School on The Rise', 'TX', 'Austin', '', 'Microschool (Waldorf)', 'Elementary', 'Small', 'Not published', ARRAY['Waldorf-rooted, strong community/philosophy differentiation']::text[], ARRAY['Waldorf schools often resist tech; likely no digital enrollment tools']::text[], 'Opportunity to modernize a philosophy-driven school''s back office', 3, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('stella-maris-collaborative', 'Stella Maris Collaborative', 'TX', 'Austin', '', 'Microschool (Catholic)', '4-8', 'Small', 'Not published', ARRAY['Low ratios, multi-age, faith-centered, service-oriented']::text[], ARRAY['Niche faith-based ops likely run on spreadsheets/manual tools']::text[], 'Faith-based niche school is a good vertical fit for FieldBook', 3, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('studio-preparatory', 'Studio Preparatory', 'TX', 'Austin', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Personalized, flexible curricula']::text[], ARRAY['Grade levels undefined on site, unclear enrollment process']::text[], 'Unclear enrollment flow = opportunity to implement clear applications module', 3, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('unity-sanctuary', 'Unity Sanctuary', 'TX', 'Austin', '', 'Project-Based', 'PreK-12', 'Small-Medium', 'Not published', ARRAY['Unique multi-generational campus model (co-working + school)']::text[], ARRAY['Complex multi-stakeholder ops (parents + kids) need robust software']::text[], 'Unique co-working/school hybrid needs multi-user account management', 4, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('villagers-microschool', 'Villagers Microschool', 'TX', 'Austin', '', 'Project-Based', '1-5', 'Small', 'Not published', ARRAY['Life-skills + business mentoring integrated into curriculum']::text[], ARRAY['Small elementary program likely lacks dedicated ops software']::text[], 'Small elementary program is a strong low-friction SaaS adoption target', 3, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('evoke-academy', 'Evoke Academy', 'TX', 'Cedar Park', '', 'Microschool', 'PreK-8', 'Small', 'Not published', ARRAY['Compact, personalized attention model']::text[], ARRAY['Broad PreK-8 span with likely manual scheduling']::text[], 'Broad grade span benefits from FieldBook''s tuition/grade management', 3, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('evoke-acton-academy', 'Evoke: Acton Academy', 'TX', 'Cedar Park', '', 'Learner-Driven (Acton)', 'Not specified', 'Small', 'Not published', ARRAY['Acton network credibility']::text[], ARRAY['Unclaimed directory listing, limited details']::text[], 'Needs claimed, complete web presence with enrollment tools', 3, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('guidepost-montessori-at-brushy-creek', 'Guidepost Montessori at Brushy Creek', 'TX', 'Cedar Park', 'https://guidepostmontessori.com', 'Montessori (Guidepost network)', 'Not specified', 'Medium (franchise)', 'Not published', ARRAY['National Montessori brand, likely has centralized systems already']::text[], ARRAY['Franchise model may already use proprietary/central software (harder sell)']::text[], 'Lower priority since franchise likely has centralized software already', 2, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('guidepost-montessori-at-cypress-creek', 'Guidepost Montessori at Cypress Creek', 'TX', 'Cedar Park', 'https://guidepostmontessori.com', 'Montessori (Guidepost network)', 'Not specified', 'Medium (franchise)', 'Not published', ARRAY['National Montessori brand']::text[], ARRAY['Franchise-level software likely already exists']::text[], 'Lower priority - franchise centralization reduces need for third-party SaaS', 2, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('12-stones-microschool', '12 Stones Microschool', 'TX', 'Houston', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Member of National Microschooling Center']::text[], ARRAY['Limited public web presence found']::text[], 'Needs foundational website + enrollment system', 3, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('e-l-l-a-learning-studio', 'E.L.L.A Learning Studio', 'TX', 'Houston', '', 'Project-Based', '9-12', 'Small', 'Not published', ARRAY['Focus on confidence/independence for high schoolers']::text[], ARRAY['Niche high-school-only model may need specialized scheduling']::text[], 'Project-based HS studio needs flexible course/credit tracking', 3, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('elderflower-montessori', 'Elderflower Montessori', 'TX', 'Houston', '', 'Montessori', 'Not specified', 'Small', 'Not published', ARRAY['Montessori credibility']::text[], ARRAY['Unclaimed listing, unclear digital presence']::text[], 'Needs claimed site + enrollment/tuition tooling', 3, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('god-s-little-people-learning-academy', 'God''s Little People Learning Academy', 'TX', 'Houston', '', 'Project-Based (faith-based)', 'PreK-2', 'Small', 'Not published', ARRAY['40+ years combined educator experience, strong early-childhood focus']::text[], ARRAY['Faith-based small program likely on manual/paper processes']::text[], 'Early-childhood faith program is a strong onboarding-friendly customer', 4, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('marvelous-treasures-academy-llc', 'Marvelous Treasures Academy, LLC', 'TX', 'Houston', '', 'Microschool (special needs focus)', 'PreK-12', 'Small', 'Not published', ARRAY['Specializes in ADHD/executive functioning support']::text[], ARRAY['Wide PreK-12 span with specialized needs likely requires custom tracking']::text[], 'Specialized needs tracking is a differentiated software opportunity', 4, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('memorial-private-school', 'Memorial Private School', 'TX', 'Houston', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Member of National Microschooling Center']::text[], ARRAY['Minimal detail available']::text[], 'Needs full digital presence and ops tooling', 3, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('northwood-cottage-school', 'Northwood Cottage School', 'TX', 'Houston', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Member of National Microschooling Center']::text[], ARRAY['Minimal detail available']::text[], 'Needs full digital presence and ops tooling', 3, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('one-hope-academy', 'One Hope Academy', 'TX', 'Houston', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Member of National Microschooling Center']::text[], ARRAY['Minimal detail available']::text[], 'Needs full digital presence and ops tooling', 3, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('prestige-wisdom-academy', 'Prestige Wisdom Academy', 'TX', 'Houston', '', 'Microschool (special ed focus)', 'PreK-12', 'Small', 'Not published', ARRAY['Specializes in special-ed and diverse learners']::text[], ARRAY['Wide grade span with individualized plans likely paper-based']::text[], 'Special-ed individualized plans need robust student tracking tools', 4, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('yellow-rose-montessori', 'Yellow Rose Montessori', 'TX', 'Houston', '', 'Montessori', 'Not specified', 'Small', 'Not published', ARRAY['Montessori credibility']::text[], ARRAY['Unclaimed listing']::text[], 'Needs claimed listing + enrollment tooling', 3, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('extraordinary-adventures-academy-katy', 'Extraordinary Adventures Academy Katy', 'TX', 'Katy', '', 'Microschool', 'PreK-12', 'Small', 'Not published', ARRAY['Wide-age personalized learning']::text[], ARRAY['Wide PreK-12 range likely hard to manage manually']::text[], 'Wide age range = strong candidate for FieldBook''s grade-level tuition tools', 4, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('extraordinary-adventures-academy-katy-an-acton-affiliate', 'Extraordinary Adventures Academy Katy: An Acton Affiliate', 'TX', 'Katy', '', 'Learner-Driven (Acton)', 'Not specified', 'Small', 'Not published', ARRAY['Acton affiliate credibility']::text[], ARRAY['Unclaimed listing']::text[], 'Needs claimed site + enrollment system', 3, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('academy-of-business-innovation', 'Academy of Business & Innovation', 'TX', 'McKinney (virtual, statewide)', 'https://academyofbusinessandinnovation.com', 'Microschool (virtual)', '9-12', 'Unknown', 'Not published', ARRAY['Fully virtual, mastery-based, CLEP-aligned, dual credit up to 60 hrs']::text[], ARRAY['Virtual model needs robust online enrollment/records tracking']::text[], 'Fully virtual HS needs strong digital enrollment/records/billing backbone', 4, 'Medium', false, 'texas', 'not_contacted', '', '', ''),
  ('morgan-preparatory-academy-for-boys', 'Morgan Preparatory Academy for Boys', 'TX', 'McKinney', '', 'Microschool (therapeutic, single-gender)', '1-4', 'Small', 'Not published', ARRAY['Therapeutic, single-gender, movement-integrated curriculum']::text[], ARRAY['Niche therapeutic program likely lacks dedicated SIS']::text[], 'Therapeutic niche school needs specialized tracking for behavior/progress', 4, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('invictus', 'Invictus', 'TX', 'Georgetown', '', 'Microschool', 'K-6', 'Small', 'Not published', ARRAY['Independent elementary program, personalized small-group instruction']::text[], ARRAY['Independent single-site school likely manual enrollment/billing']::text[], 'Independent elementary program close to Sage Field''s Round Rock service area', 4, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('invictus-an-acton-academy', 'Invictus: An Acton Academy', 'TX', 'Georgetown', '', 'Learner-Driven (Acton)', 'Not specified', 'Small', 'Not published', ARRAY['Acton network credibility']::text[], ARRAY['Unclaimed listing']::text[], 'Needs claimed site + enrollment system', 3, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('hedge-school-cooperative', 'Hedge School Cooperative', 'TX', 'Dripping Springs', '', 'Microschool (secular co-op)', '9-12', 'Small', 'Not published', ARRAY['Inclusive, secular co-op community model for teens']::text[], ARRAY['Co-op structure with shared teaching likely lacks central software']::text[], 'Co-op model needs shared scheduling/billing across multiple teaching families', 3, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('kinder-academy-prep-school-kaps', 'Kinder Academy Prep School (KAPS)', 'TX', 'Georgetown', 'https://kinderacademyprepschool.com', 'Microschool (Prenda-powered)', 'K-3 (ages 4-8)', '10 students max', 'Not published, 1-4pm daily', ARRAY['Prenda-powered model, experienced 33-yr educator founder, launching Fall 2026']::text[], ARRAY['New launch (2026-27) means no existing systems in place — greenfield opportunity']::text[], 'Brand-new school launching with no existing software — ideal greenfield MudKitchen prospect', 5, 'High', false, 'texas', 'not_contacted', 'Kimberly Lind', 'contact@kinderacademyprepschool.com', '(737) 775-8833'),
  ('ladies-and-gents-private-academy-houston-prenda', 'Ladies and Gents Private Academy Houston (Prenda)', 'TX', 'Houston', 'https://microschools.prenda.com/ms/ladiesandgentsprivateacademy', 'Microschool (Prenda network)', 'K-8', 'Small', 'Not published', ARRAY['Prenda-network backed, TEFA participant']::text[], ARRAY['Prenda network may already provide guide-level tools, but school-level ops still manual']::text[], 'Prenda guides often lack dedicated tuition/enrollment tooling beyond Prenda''s core app', 3, 'Medium', false, 'texas', 'not_contacted', 'Keri Ford', '', '(844) 477-3632'),
  ('arga-academics-prenda', 'ARGA Academics (Prenda)', 'TX', 'Richardson', 'https://www.prenda.com', 'Microschool (Prenda network)', 'K-8', 'Small', 'Not published', ARRAY['Prenda-network backed, TEFA participant']::text[], ARRAY['Same as above - Prenda tools may not cover full school-level operations']::text[], 'Prenda-affiliated school could still need dedicated site/tuition/app management', 3, 'Medium', false, 'texas', 'not_contacted', 'Keri Ford', '', '(844) 477-3632'),
  ('teeny-tiny-academy', 'Teeny Tiny Academy', 'TX', 'Copperas Cove', '', 'Early Childhood Microschool', 'PreK', 'Small', 'Not published', ARRAY['TEFA participant, local family-run']::text[], ARRAY['Family-run small program with likely no digital ops tools']::text[], 'Family-run early childhood program is a strong low-cost SaaS adoption candidate', 3, 'Medium', false, 'texas', 'not_contacted', 'Venesha Grinner', '', '(254) 598-0828'),
  ('aristotle-s-garden-micro-academy', 'Aristotle''s Garden Micro-Academy', 'TX', 'San Antonio', '', 'Microschool (mastery-based)', '4-6', 'Small (9-13 age range served)', 'Not published', ARRAY['Mastery-based, Socratic philosophy, intentional small community']::text[], ARRAY['Narrow grade band + mastery model needs custom progress tracking, not typical SIS']::text[], 'Mastery-based model needs flexible, non-grade-based progress & billing tracking', 4, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('tripoint-schools', 'TriPoint Schools', 'TX', 'San Antonio', 'https://main.tripointacademyschools.org', 'Microschool (community-designed)', '9-12', '~160 students, 2 campuses', 'Not published', ARRAY['Multi-campus, larger scale (160 students) than typical microschool, strong community design']::text[], ARRAY['Larger multi-campus operation likely needs centralized cross-campus system']::text[], 'Multi-campus scale is a strong upsell case — needs unified cross-campus ops platform', 4, 'Medium', false, 'texas', 'not_contacted', '', '', ''),
  ('the-unschool-of-san-antonio', 'The Unschool of San Antonio', 'TX', 'San Antonio', '', 'Nature-based Microschool', 'Ages 5-8', 'Small', 'Not published', ARRAY['Nature-based, child-centered — strong philosophical overlap with Sage Field']::text[], ARRAY['Small nature program likely runs informally, no digital enrollment']::text[], 'Direct outdoor-education philosophical match — ideal MudKitchen prospect', 5, 'Medium', false, 'texas', 'not_contacted', '', '', '(210) 920-1853'),
  ('the-humanist-academy-dallas-fort-worth-area', 'The Humanist Academy (Dallas/Fort Worth Area)', 'TX', 'Irving', '', 'Microschool', 'K-12', 'Small', 'Not published', ARRAY['Serves broad DFW area, wide K-12 span']::text[], ARRAY['Wide grade span across a metro area likely needs remote/multi-site tools']::text[], 'Wide-area service model needs strong online enrollment/application system', 3, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('arise-leadership-academy', 'Arise Leadership Academy', 'TX', 'Farmers Branch', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['DFW-area presence']::text[], ARRAY['Limited public info']::text[], 'Needs foundational website/ops tooling', 3, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('acton-academy-lakewood', 'Acton Academy Lakewood', 'TX', 'Dallas', '', 'Learner-Driven (Acton)', 'Not specified', 'Small', 'Not published', ARRAY['Acton network credibility in Dallas market']::text[], ARRAY['Manual ops typical of Acton studios']::text[], 'Dallas market Acton studio, good expansion target', 3, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('lift-schoolhouse', 'LIFT Schoolhouse', 'TX', 'Keller', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['DFW-area presence']::text[], ARRAY['Limited public info']::text[], 'Needs foundational website/ops tooling', 3, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('b-e-a-m-academy', 'B.E.A.M. Academy', 'TX', 'Arlington', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['DFW-area presence']::text[], ARRAY['Limited public info']::text[], 'Needs foundational website/ops tooling', 3, 'Low', false, 'texas', 'not_contacted', '', '', ''),
  ('brilliant-minds-christian-academy', 'Brilliant Minds Christian Academy', 'TX', 'Humble', '', 'Microschool (Christian)', 'PreK-2', 'Small', 'Not published', ARRAY['Christ-centered, early-grades focus']::text[], ARRAY['Faith-based small program likely manual admin']::text[], 'Early-grades faith school is strong onboarding-friendly customer', 3, 'Low', false, 'texas', 'not_contacted', '', '', '')

on conflict (school_id) do nothing;

-- Verification (run after import)
-- Expect 52 new texas-source rows if first run; 0 rows if re-run immediately after.
select count(*) as inserted_recently
from public.schools
where source_file = 'texas'
  and school_id in (
    'acton-academy-austin-main-campus',
    'acton-academy-bee-cave',
    'ascent-an-acton-academy',
    'acton-academy-dripping-springs',
    'acton-academy-fort-worth',
    'acton-academy-amarillo',
    'acton-academy-beaumont',
    'acton-academy-corpus-christi',
    'acton-academy-cy-fair',
    'acton-academy-mckinney',
    'acton-leadership-academy-champions-klein',
    'elite-flexi-school',
    'long-view-micro-school',
    'school-on-the-rise',
    'stella-maris-collaborative',
    'studio-preparatory',
    'unity-sanctuary',
    'villagers-microschool',
    'evoke-academy',
    'evoke-acton-academy',
    'guidepost-montessori-at-brushy-creek',
    'guidepost-montessori-at-cypress-creek',
    '12-stones-microschool',
    'e-l-l-a-learning-studio',
    'elderflower-montessori',
    'god-s-little-people-learning-academy',
    'marvelous-treasures-academy-llc',
    'memorial-private-school',
    'northwood-cottage-school',
    'one-hope-academy',
    'prestige-wisdom-academy',
    'yellow-rose-montessori',
    'extraordinary-adventures-academy-katy',
    'extraordinary-adventures-academy-katy-an-acton-affiliate',
    'academy-of-business-innovation',
    'morgan-preparatory-academy-for-boys',
    'invictus',
    'invictus-an-acton-academy',
    'hedge-school-cooperative',
    'kinder-academy-prep-school-kaps',
    'ladies-and-gents-private-academy-houston-prenda',
    'arga-academics-prenda',
    'teeny-tiny-academy',
    'aristotle-s-garden-micro-academy',
    'tripoint-schools',
    'the-unschool-of-san-antonio',
    'the-humanist-academy-dallas-fort-worth-area',
    'arise-leadership-academy',
    'acton-academy-lakewood',
    'lift-schoolhouse',
    'b-e-a-m-academy',
    'brilliant-minds-christian-academy'
  );

-- Confirm skipped duplicates still exist (should return 11 rows)
select school_id, name
from public.schools
where school_id in (
  'acton-academy-nw-austin',
  'acton-houston-heights',
  'ahb-community-school',
  'athena-micro-academy-austin',
  'natures-schoolhouse-microschool',
  'mirus-academy',
  'apogee-dripping-springs',
  'esteam-academy-round-rock',
  'the-woodlands-microschool',
  'spyrja-academy',
  'brighter-futures-microschool'
)
order by name;

