-- 2026-08-14: Import California microschools from california_microschools.csv (59 new rows)
-- No duplicates skipped — all rows are new to public.schools
-- Idempotent: ON CONFLICT (school_id) DO NOTHING

insert into public.schools (
  school_id,
  name,
  state,
  location,
  website,
  school_model,
  grades,
  estimated_size,
  tuition_schedule,
  strengths,
  pain_points,
  software_fit_reason,
  priority_score,
  confidence,
  is_closing,
  source_file,
  crm_status,
  contact_name,
  contact_email,
  contact_phone
) values

  ('wild-child-san-diego-nature-school', 'Wild Child San Diego Nature School', 'CA', 'San Diego (Mission Bay)', 'https://www.wildchildsd.com', 'Forest/Nature School', 'Not specified', 'Small', 'Not published', ARRAY['Nature-based, held at Mission Bay — direct philosophical overlap with Sage Field']::text[], ARRAY['Outdoor meetup format with variable/weather-dependent locations likely hard to manage manually']::text[], 'Direct outdoor-education philosophical match — ideal MudKitchen prospect', 5, 'Medium', false, 'california', 'not_contacted', '', '', ''),
  ('ekballo-kids-academy', 'Ekballo Kids Academy', 'CA', 'California (Prenda network)', 'https://microschools.prenda.com/ms/ekballo', 'Microschool (Prenda-powered, faith-based)', 'Not specified', 'Small', 'Not published', ARRAY['Faith-based, experienced educator/guide, active for 2026-27 school year']::text[], ARRAY['Prenda tools may not cover full school-level ops (tuition, site, apps)']::text[], 'Prenda-affiliated faith school could still need dedicated site/tuition/app management', 3, 'Medium', false, 'california', 'not_contacted', '', '', ''),
  ('precious-blood-school-rampart-village', 'Precious Blood School (Rampart Village)', 'CA', 'Los Angeles', 'https://www.lacatholicschools.org', 'Microschool (Catholic network)', 'Not specified', 'Small-Medium', 'Not published', ARRAY['Part of LA Catholic Schools'' formal Microschools Network, multi-age pedagogy + blended learning']::text[], ARRAY['Diocese-run network likely already has centralized Catholic-school SIS']::text[], 'Diocese network may have existing systems — lower priority unless targeting site-level gaps', 2, 'Medium', false, 'california', 'not_contacted', '', '', ''),
  ('st-athanasius-school', 'St. Athanasius School', 'CA', 'Long Beach', 'https://www.lacatholicschools.org', 'Microschool (Catholic network)', 'Not specified', 'Small-Medium', 'Not published', ARRAY['Part of LA Catholic Schools'' Microschools Network, whole-child approach']::text[], ARRAY['Diocese-run network likely already has centralized Catholic-school SIS']::text[], 'Diocese network may have existing systems — lower priority unless targeting site-level gaps', 2, 'Medium', false, 'california', 'not_contacted', '', '', ''),
  ('holy-name-of-jesus-school', 'Holy Name of Jesus School', 'CA', 'Los Angeles', 'https://www.lacatholicschools.org', 'Microschool (Catholic network)', 'Not specified', 'Small-Medium', 'Not published', ARRAY['Part of LA Catholic Schools'' Microschools Network']::text[], ARRAY['Diocese-run network likely already has centralized Catholic-school SIS']::text[], 'Diocese network may have existing systems — lower priority unless targeting site-level gaps', 2, 'Medium', false, 'california', 'not_contacted', '', '', ''),
  ('holy-redeemer-st-james-school', 'Holy Redeemer - St. James School', 'CA', 'Los Angeles', 'https://www.lacatholicschools.org', 'Microschool (Catholic network)', 'Not specified', 'Small-Medium', 'Not published', ARRAY['Part of LA Catholic Schools'' Microschools Network']::text[], ARRAY['Diocese-run network likely already has centralized Catholic-school SIS']::text[], 'Diocese network may have existing systems — lower priority unless targeting site-level gaps', 2, 'Medium', false, 'california', 'not_contacted', '', '', ''),
  ('st-rose-of-lima-school', 'St. Rose of Lima School', 'CA', 'Maywood', 'https://www.lacatholicschools.org', 'Microschool (Catholic network)', 'Not specified', 'Small-Medium', 'Not published', ARRAY['Part of LA Catholic Schools'' Microschools Network']::text[], ARRAY['Diocese-run network likely already has centralized Catholic-school SIS']::text[], 'Diocese network may have existing systems — lower priority unless targeting site-level gaps', 2, 'Medium', false, 'california', 'not_contacted', '', '', ''),
  ('acton-academy-san-francisco', 'Acton Academy San Francisco', 'CA', 'San Francisco', 'https://sanfrancisco.actonacademy.org', 'Learner-Driven (Acton)', 'K-8', '~30-50', 'Not published', ARRAY['Established Acton network presence in a major hub city']::text[], ARRAY['Wide K-8 span likely strains manual admin/billing']::text[], 'Wide-span Acton studio in a major hub needs FieldBook''s tuition/grade tools', 4, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('wildflower-schools-bay-area', 'Wildflower Schools - Bay Area', 'CA', 'San Francisco / Redwood City / Palo Alto', 'https://www.wildflowerschools.org', 'Montessori (Wildflower network)', 'PreK-K', 'Multiple micro-sites (small)', 'Not published', ARRAY['Distributed Montessori micro-site network model across the Bay Area, teacher-led']::text[], ARRAY['Multi-site distributed network likely needs unified cross-site enrollment/billing']::text[], 'Multi-site distributed micro-network is a strong upsell case for centralized ops across locations', 4, 'Medium', false, 'california', 'not_contacted', '', '', ''),
  ('sequoia-sage-microschool', 'Sequoia Sage Microschool', 'CA', 'San Francisco', '', 'Forest/Nature', 'Elementary', 'Small', 'Not published', ARRAY['Nature-themed branding suggests outdoor programming overlap with Sage Field']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Nature-themed branding overlaps directly with Sage Field''s outdoor philosophy', 4, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('the-nueva-school-microschool-pilot', 'The Nueva School Microschool Pilot', 'CA', 'San Francisco/Bay Area', '', 'Project-Based (gifted)', 'Elementary-Middle', 'Small', 'Not published', ARRAY['Gifted-focused pilot program under established Nueva brand']::text[], ARRAY['Pilot program under larger institution may already have centralized admin tools']::text[], 'Pilot under larger institution — lower priority unless targeting the microschool unit specifically', 2, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('golden-gate-microschool', 'Golden Gate Microschool', 'CA', 'San Francisco', '', 'Microschool', 'K-5', 'Small', 'Not published', ARRAY['Established single-site urban program']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Low-friction SaaS adoption candidate', 3, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('bay-discovery-microschool', 'Bay Discovery Microschool', 'CA', 'Redwood City', '', 'Project-Based', 'K-8', 'Small', 'Not published', ARRAY['Discovery/inquiry-based curriculum, established Peninsula presence']::text[], ARRAY['Wide K-8 span likely strains manual admin']::text[], 'Wide-span inquiry-based program is a strong fit for flexible progress tracking', 3, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('redwood-explorers-academy', 'Redwood Explorers Academy', 'CA', 'Redwood City', '', 'Forest/Nature', 'Elementary', 'Small', 'Not published', ARRAY['Nature-themed branding, Peninsula location — philosophical overlap with Sage Field']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Nature-themed branding overlaps directly with Sage Field''s outdoor philosophy', 4, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('peninsula-bridge-microschool', 'Peninsula Bridge Microschool', 'CA', 'Palo Alto', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established Silicon Valley-adjacent presence']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Tech-savvy parent base in Palo Alto is a strong early-adopter market for SaaS', 3, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('acton-academy-palo-alto', 'Acton Academy Palo Alto', 'CA', 'Palo Alto', 'https://paloalto.actonacademy.org', 'Learner-Driven (Acton)', 'K-8', '~30-50', 'Not published', ARRAY['Established Acton network presence in tech-hub market']::text[], ARRAY['Wide K-8 span likely strains manual admin/billing']::text[], 'Tech-hub Acton studio is a strong early-adopter market for SaaS', 4, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('capital-city-microschool', 'Capital City Microschool', 'CA', 'Sacramento', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site program in state capital market']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Low-friction SaaS adoption candidate', 3, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('sacramento-nature-collective', 'Sacramento Nature Collective', 'CA', 'Sacramento', '', 'Forest/Nature Co-op', 'Not specified', 'Small', 'Not published', ARRAY['Nature-based co-op — philosophical overlap with Sage Field']::text[], ARRAY['Co-op structure with shared teaching likely lacks central software']::text[], 'Nature-based co-op needs shared scheduling/billing across multiple teaching families', 4, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('bright-path-learning-center', 'Bright Path Learning Center', 'CA', 'Alameda', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site East Bay presence']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Low-friction SaaS adoption candidate', 3, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('bonita-microschool-collective', 'Bonita Microschool Collective', 'CA', 'Bonita', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site San Diego-adjacent presence']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Low-friction SaaS adoption candidate', 3, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('burbank-innovators-academy', 'Burbank Innovators Academy', 'CA', 'Burbank', '', 'Microschool (STEAM)', 'Not specified', 'Small', 'Not published', ARRAY['STEAM-focused, LA-adjacent market']::text[], ARRAY['Small single-site likely manual admin']::text[], 'STEAM-focused school is a strong candidate for progress/portfolio tracking tools', 3, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('calabasas-discovery-school', 'Calabasas Discovery School', 'CA', 'Calabasas', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site affluent-market presence']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Affluent market with tech-savvy families is a strong early-adopter candidate', 3, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('campbell-community-microschool', 'Campbell Community Microschool', 'CA', 'Campbell', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site South Bay presence']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Low-friction SaaS adoption candidate', 3, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('carlsbad-coastal-learning', 'Carlsbad Coastal Learning', 'CA', 'Carlsbad', '', 'Forest/Nature', 'Not specified', 'Small', 'Not published', ARRAY['Coastal/outdoor branding — philosophical overlap with Sage Field']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Coastal outdoor branding overlaps directly with Sage Field''s philosophy', 4, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('claremont-colleges-prep-microschool', 'Claremont Colleges Prep Microschool', 'CA', 'Claremont', '', 'Project-Based', 'Middle-High', 'Small', 'Not published', ARRAY['College-prep positioning near Claremont Colleges']::text[], ARRAY['Small single-site likely manual admin']::text[], 'College-prep niche school benefits from transcript/credit tracking tools', 3, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('concord-valley-microschool', 'Concord Valley Microschool', 'CA', 'Concord', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site East Bay presence']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Low-friction SaaS adoption candidate', 3, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('culver-city-creative-academy', 'Culver City Creative Academy', 'CA', 'Culver City', '', 'Project-Based (arts)', 'Not specified', 'Small', 'Not published', ARRAY['Arts-integrated curriculum, LA-adjacent market']::text[], ARRAY['Arts electives likely need custom scheduling']::text[], 'Arts-integrated program needs flexible course & tuition tracking beyond basic SIS', 3, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('el-monte-family-microschool', 'El Monte Family Microschool', 'CA', 'El Monte', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site San Gabriel Valley presence']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Low-friction SaaS adoption candidate', 3, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('escondido-explorers', 'Escondido Explorers', 'CA', 'Escondido', '', 'Forest/Nature', 'Not specified', 'Small', 'Not published', ARRAY['Nature-themed branding — philosophical overlap with Sage Field']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Nature-themed branding overlaps directly with Sage Field''s outdoor philosophy', 4, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('fallbrook-farm-school', 'Fallbrook Farm School', 'CA', 'Fallbrook', '', 'Forest/Nature (farm-based)', 'Not specified', 'Small', 'Not published', ARRAY['Farm-based, rural North San Diego County — direct philosophical overlap with Sage Field']::text[], ARRAY['Rural farm program likely runs informally, no digital enrollment']::text[], 'Direct outdoor/farm-based philosophical match — ideal MudKitchen prospect', 5, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('hollister-heritage-microschool', 'Hollister Heritage Microschool', 'CA', 'Hollister', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site Central Coast-adjacent presence']::text[], ARRAY['Rural market likely lean staff, manual admin']::text[], 'Rural lean-team school is a strong candidate for affordable all-in-one SaaS', 3, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('huntington-beach-surf-study', 'Huntington Beach Surf & Study', 'CA', 'Huntington Beach', '', 'Project-Based (outdoor/coastal)', 'Not specified', 'Small', 'Not published', ARRAY['Coastal activity-based curriculum — philosophical overlap with Sage Field']::text[], ARRAY['Non-traditional activity-based curriculum likely hard to schedule/bill manually']::text[], 'Coastal activity-based curriculum needs flexible scheduling tools', 4, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('la-ca-ada-flintridge-microschool', 'La Cañada Flintridge Microschool', 'CA', 'La Cañada Flintridge', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site affluent-market presence']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Affluent market with tech-savvy families is a strong early-adopter candidate', 3, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('la-mesa-learning-collective', 'La Mesa Learning Collective', 'CA', 'La Mesa', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site San Diego-adjacent presence']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Low-friction SaaS adoption candidate', 3, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('laguna-hills-micro-academy', 'Laguna Hills Micro Academy', 'CA', 'Laguna Hills', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site Orange County presence']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Low-friction SaaS adoption candidate', 3, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('lake-forest-learning-studio', 'Lake Forest Learning Studio', 'CA', 'Lake Forest', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site Orange County presence']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Low-friction SaaS adoption candidate', 3, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('lancaster-desert-microschool', 'Lancaster Desert Microschool', 'CA', 'Lancaster', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site Antelope Valley presence, underserved market']::text[], ARRAY['Rural/exurban market likely lean staff, manual admin']::text[], 'Exurban lean-team school is a strong candidate for affordable all-in-one SaaS', 3, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('livermore-valley-microschool', 'Livermore Valley Microschool', 'CA', 'Livermore', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site Tri-Valley presence']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Low-friction SaaS adoption candidate', 3, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('monrovia-foothills-academy', 'Monrovia Foothills Academy', 'CA', 'Monrovia', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site San Gabriel Valley presence']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Low-friction SaaS adoption candidate', 3, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('mountain-view-innovators', 'Mountain View Innovators', 'CA', 'Mountain View', '', 'Microschool (STEAM)', 'Not specified', 'Small', 'Not published', ARRAY['STEAM-focused, Silicon Valley market']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Tech-hub STEAM school is a strong early-adopter market for SaaS', 3, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('northridge-community-microschool', 'Northridge Community Microschool', 'CA', 'Northridge', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site San Fernando Valley presence']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Low-friction SaaS adoption candidate', 3, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('pasadena-prep-microschool', 'Pasadena Prep Microschool', 'CA', 'Pasadena', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site San Gabriel Valley presence']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Low-friction SaaS adoption candidate', 3, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('pleasanton-tri-valley-microschool', 'Pleasanton Tri-Valley Microschool', 'CA', 'Pleasanton', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site Tri-Valley presence']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Low-friction SaaS adoption candidate', 3, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('redding-northstate-microschool', 'Redding Northstate Microschool', 'CA', 'Redding', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site Northern CA presence, underserved market']::text[], ARRAY['Rural market likely lean staff, manual admin']::text[], 'Rural lean-team school is a strong candidate for affordable all-in-one SaaS', 4, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('rocklin-valley-microschool', 'Rocklin Valley Microschool', 'CA', 'Rocklin', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site Sacramento-adjacent presence']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Low-friction SaaS adoption candidate', 3, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('roseville-roots-academy', 'Roseville Roots Academy', 'CA', 'Roseville', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site Sacramento-adjacent presence']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Low-friction SaaS adoption candidate', 3, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('north-county-nature-school', 'North County Nature School', 'CA', 'San Diego County', '', 'Forest/Nature', 'Not specified', 'Small', 'Not published', ARRAY['Nature-based, San Diego County — direct philosophical overlap with Sage Field']::text[], ARRAY['Small nature program likely runs informally, no digital enrollment']::text[], 'Direct outdoor-education philosophical match — ideal MudKitchen prospect', 5, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('silicon-valley-microschool', 'Silicon Valley Microschool', 'CA', 'San Jose', '', 'Microschool (STEAM)', 'Not specified', 'Small', 'Not published', ARRAY['STEAM-focused, tech-hub market with tech-savvy parents']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Tech-hub STEAM school with tech-savvy parents is a strong early-adopter market', 3, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('santa-ana-community-microschool', 'Santa Ana Community Microschool', 'CA', 'Santa Ana', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site Orange County presence']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Low-friction SaaS adoption candidate', 3, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('santa-barbara-coastal-academy', 'Santa Barbara Coastal Academy', 'CA', 'Santa Barbara', '', 'Forest/Nature (coastal)', 'Not specified', 'Small', 'Not published', ARRAY['Coastal/outdoor branding — philosophical overlap with Sage Field']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Coastal outdoor branding overlaps directly with Sage Field''s philosophy', 4, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('santa-clarita-valley-microschool', 'Santa Clarita Valley Microschool', 'CA', 'Santa Clarita', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site presence in growing suburb']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Low-friction SaaS adoption candidate', 3, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('santa-cruz-redwood-learning', 'Santa Cruz Redwood Learning', 'CA', 'Santa Cruz', '', 'Forest/Nature', 'Not specified', 'Small', 'Not published', ARRAY['Redwood/nature branding — direct philosophical overlap with Sage Field']::text[], ARRAY['Small nature program likely runs informally, no digital enrollment']::text[], 'Direct outdoor-education philosophical match — ideal MudKitchen prospect', 5, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('santa-monica-beach-microschool', 'Santa Monica Beach Microschool', 'CA', 'Santa Monica', '', 'Project-Based (outdoor/coastal)', 'Not specified', 'Small', 'Not published', ARRAY['Coastal activity-based curriculum — philosophical overlap with Sage Field']::text[], ARRAY['Non-traditional activity-based curriculum likely hard to schedule/bill manually']::text[], 'Coastal activity-based curriculum needs flexible scheduling tools', 4, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('sausalito-bay-microschool', 'Sausalito Bay Microschool', 'CA', 'Sausalito', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site Marin County presence, affluent market']::text[], ARRAY['Affluent small market likely manual admin']::text[], 'Affluent market with tech-savvy families is a strong early-adopter candidate', 3, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('temple-city-learning-studio', 'Temple City Learning Studio', 'CA', 'Temple City', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site San Gabriel Valley presence']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Low-friction SaaS adoption candidate', 3, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('thousand-oaks-microschool', 'Thousand Oaks Microschool', 'CA', 'Thousand Oaks', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site Conejo Valley presence']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Low-friction SaaS adoption candidate', 3, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('valley-center-ranch-school', 'Valley Center Ranch School', 'CA', 'Valley Center', '', 'Forest/Nature (farm/ranch)', 'Not specified', 'Small', 'Not published', ARRAY['Ranch/farm-based, rural San Diego County — direct philosophical overlap with Sage Field']::text[], ARRAY['Rural farm program likely runs informally, no digital enrollment']::text[], 'Direct outdoor/farm-based philosophical match — ideal MudKitchen prospect', 5, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('venice-beach-micro-academy', 'Venice Beach Micro Academy', 'CA', 'Venice', '', 'Project-Based (arts/outdoor)', 'Not specified', 'Small', 'Not published', ARRAY['Coastal, arts + outdoor blend — philosophical overlap with Sage Field']::text[], ARRAY['Non-traditional activity-based curriculum likely hard to schedule/bill manually']::text[], 'Coastal outdoor/arts blend needs flexible scheduling tools', 4, 'Low', false, 'california', 'not_contacted', '', '', ''),
  ('visalia-central-valley-microschool', 'Visalia Central Valley Microschool', 'CA', 'Visalia', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site Central Valley presence, underserved market']::text[], ARRAY['Rural market likely lean staff, manual admin']::text[], 'Rural lean-team school is a strong candidate for affordable all-in-one SaaS', 3, 'Low', false, 'california', 'not_contacted', '', '', '')

on conflict (school_id) do nothing;

-- Verification (run after import)
-- Expect 59 rows for the imported California batch.
select count(*) as california_import_count
from public.schools
where source_file = 'california'
  and school_id in (
    'wild-child-san-diego-nature-school',
    'ekballo-kids-academy',
    'precious-blood-school-rampart-village',
    'st-athanasius-school',
    'holy-name-of-jesus-school',
    'holy-redeemer-st-james-school',
    'st-rose-of-lima-school',
    'acton-academy-san-francisco',
    'wildflower-schools-bay-area',
    'sequoia-sage-microschool',
    'the-nueva-school-microschool-pilot',
    'golden-gate-microschool',
    'bay-discovery-microschool',
    'redwood-explorers-academy',
    'peninsula-bridge-microschool',
    'acton-academy-palo-alto',
    'capital-city-microschool',
    'sacramento-nature-collective',
    'bright-path-learning-center',
    'bonita-microschool-collective',
    'burbank-innovators-academy',
    'calabasas-discovery-school',
    'campbell-community-microschool',
    'carlsbad-coastal-learning',
    'claremont-colleges-prep-microschool',
    'concord-valley-microschool',
    'culver-city-creative-academy',
    'el-monte-family-microschool',
    'escondido-explorers',
    'fallbrook-farm-school',
    'hollister-heritage-microschool',
    'huntington-beach-surf-study',
    'la-ca-ada-flintridge-microschool',
    'la-mesa-learning-collective',
    'laguna-hills-micro-academy',
    'lake-forest-learning-studio',
    'lancaster-desert-microschool',
    'livermore-valley-microschool',
    'monrovia-foothills-academy',
    'mountain-view-innovators',
    'northridge-community-microschool',
    'pasadena-prep-microschool',
    'pleasanton-tri-valley-microschool',
    'redding-northstate-microschool',
    'rocklin-valley-microschool',
    'roseville-roots-academy',
    'north-county-nature-school',
    'silicon-valley-microschool',
    'santa-ana-community-microschool',
    'santa-barbara-coastal-academy',
    'santa-clarita-valley-microschool',
    'santa-cruz-redwood-learning',
    'santa-monica-beach-microschool',
    'sausalito-bay-microschool',
    'temple-city-learning-studio',
    'thousand-oaks-microschool',
    'valley-center-ranch-school',
    'venice-beach-micro-academy',
    'visalia-central-valley-microschool'
  );

-- Sanity: total california source rows (expect 59 after first run)
select count(*) as california_source_total
from public.schools
where source_file = 'california';

