-- 2026-08-14: Import Arizona microschools from arizona_microschools.csv (51 new rows)
-- Skips 1 school already in public.schools:
--   Desert Sun Ranch Academy (desert-sun-ranch-academy)
-- Idempotent: ON CONFLICT (school_id) DO NOTHING

insert into public.schools (
  school_id,
  name,
  state,
  location,
  website,
  school_model,
  grades,
  estimated_size,
  tuition_schedule,
  strengths,
  pain_points,
  software_fit_reason,
  priority_score,
  confidence,
  is_closing,
  source_file,
  crm_status,
  contact_name,
  contact_email,
  contact_phone
) values

  ('acton-academy-east-valley', 'Acton Academy East Valley', 'AZ', 'Queen Creek', 'https://eastvalley.actonacademy.org', 'Learner-Driven (Acton)', 'K-12', '~40-60', 'Not published', ARRAY['Self-directed learning, Acton network credibility, wide K-12 span']::text[], ARRAY['No visible integrated tuition/application system, wide grade span strains manual tracking']::text[], 'Wide K-12 span needs FieldBook''s grade-based tuition and application management', 4, 'Low', false, 'arizona', 'not_contacted', '', '', ''),
  ('off-trail-adventures-santan-shredders', 'Off Trail Adventures (SanTan Shredders)', 'AZ', 'Queen Creek', '', 'Microschool (outdoor/adventure)', 'Not specified', 'Small', 'Not published', ARRAY['Outdoor/adventure-based programming — strong philosophical overlap with Sage Field']::text[], ARRAY['Unclaimed listing, minimal digital presence']::text[], 'Direct outdoor-education philosophical match — ideal MudKitchen prospect', 5, 'Low', false, 'arizona', 'not_contacted', '', '', ''),
  ('the-learning-vine', 'The Learning Vine', 'AZ', 'Queen Creek', '', 'Microschool', 'K-8', 'Small', 'Not published', ARRAY['Hands-on, real-world learning with built-in enrichment courses']::text[], ARRAY['Wide K-8 span with enrichment add-ons likely tracked manually']::text[], 'Enrichment/electives layered on core curriculum need flexible scheduling tools', 3, 'Low', false, 'arizona', 'not_contacted', '', '', ''),
  ('ato-academy', 'ATO Academy', 'AZ', 'Phoenix', '', 'Project-Based (performing arts)', 'K-12', 'Small', 'Not published', ARRAY['Combines performing arts/creative expression with culturally responsive, project-based learning']::text[], ARRAY['Wide K-12 span with arts electives likely needs custom scheduling']::text[], 'Arts-integrated K-12 program needs flexible course & tuition tracking beyond basic SIS', 3, 'Low', false, 'arizona', 'not_contacted', '', '', ''),
  ('gifted-microschool-at-the-gifted-collective', 'Gifted Microschool at The Gifted Collective', 'AZ', 'Phoenix', 'https://thegiftedcollective.com', 'Microschool (gifted)', 'Not specified', 'Small', 'Not published', ARRAY['Specializes in gifted/curious learners, two academies under one roof']::text[], ARRAY['Multi-academy structure under one brand likely needs unified backend']::text[], 'Multi-program brand (2 academies) needs centralized ops across sub-schools', 4, 'Medium', false, 'arizona', 'not_contacted', '', 'Inquiries@TheGiftedCollective.com', '(623) 986-8408'),
  ('peak-learning-academy', 'Peak Learning Academy', 'AZ', 'Phoenix (New River)', 'https://peak-learning.org', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['National Microschooling Center member, established rural-adjacent presence']::text[], ARRAY['Limited digital enrollment/tuition tooling visible']::text[], 'Needs modern enrollment/tuition system for growing rural-adjacent program', 3, 'Medium', false, 'arizona', 'not_contacted', '', 'amy@peak-learning.org', '(623) 687-7878'),
  ('sunshine-learning-academy', 'Sunshine Learning Academy', 'AZ', 'Phoenix', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['National Microschooling Center member']::text[], ARRAY['Minimal public web presence found']::text[], 'Needs foundational website + enrollment system', 3, 'Low', false, 'arizona', 'not_contacted', '', '', ''),
  ('the-h-e-a-r-t-center', 'The H.E.A.R.T. Center', 'AZ', 'Phoenix', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['National Microschooling Center member']::text[], ARRAY['Minimal public web presence found']::text[], 'Needs foundational website + enrollment system', 3, 'Low', false, 'arizona', 'not_contacted', '', '', ''),
  ('vita-high-school', 'Vita High School', 'AZ', 'Phoenix', '', 'Microschool', 'High School', 'Small', 'Not published', ARRAY['National Microschooling Center member, HS-focused niche']::text[], ARRAY['Minimal public web presence found']::text[], 'HS-only niche school needs credit/transcript-aware enrollment tooling', 3, 'Low', false, 'arizona', 'not_contacted', '', '', ''),
  ('kat-s-community-microschool', 'Kat''s Community Microschool', 'AZ', 'Phoenix', 'https://katscommunitymicroschool.com', 'Microschool (Prenda-powered)', '3-6', 'Max 10 students', 'Not published', ARRAY['Prenda-powered, tiny cohort (10 max), personalized/student-driven, ESA-aligned']::text[], ARRAY['Tiny single-operator school likely runs entirely manually via email/text']::text[], 'Tiny single-operator Prenda school is a prime low-friction adoption target for full ops/tuition suite', 5, 'High', false, 'arizona', 'not_contacted', 'K.L. Graves', 'K.L.Graves1982@gmail.com', '(602) 946-2332'),
  ('aloha-micro-academy', 'Aloha Micro Academy', 'AZ', 'Phoenix & Tempe', 'https://alohamicroacademy.org', 'Microschool', 'Not specified', 'Small (2 campuses)', 'Not published', ARRAY['Multi-campus (Phoenix + Tempe), established brand']::text[], ARRAY['Two campuses likely need unified cross-site management']::text[], 'Multi-site operation is a strong upsell case for centralized cross-campus platform', 4, 'Medium', false, 'arizona', 'not_contacted', '', '', ''),
  ('anchor-microschools', 'Anchor Microschools', 'AZ', 'Maricopa', 'https://anchormicroschools.com', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established local brand with clear enrollment contact']::text[], ARRAY['Enrollment process appears email-based, not automated']::text[], 'Email-based enrollment is a clear gap for FieldBook''s application module', 3, 'Medium', false, 'arizona', 'not_contacted', '', 'Enrollment@AnchorMicroschools.com', ''),
  ('az-steam-academy', 'AZ Steam Academy', 'AZ', 'Sierra Vista', 'https://azsteam.com', 'Microschool (STEAM)', 'Not specified', 'Small', 'Not published', ARRAY['STEAM-focused curriculum in an underserved rural market']::text[], ARRAY['Rural market likely lean staff, manual admin']::text[], 'Rural STEAM program is strong lean-team candidate for all-in-one SaaS', 3, 'Low', false, 'arizona', 'not_contacted', '', '', ''),
  ('bmf-microschools', 'BMF Microschools', 'AZ', 'Statewide (Black Mothers Forums network)', 'https://bmfmicroschools.org', 'Microschool network', 'Not specified', 'Multiple sites', 'Not published', ARRAY['Community-driven network model, mission-aligned equity focus']::text[], ARRAY['Network of multiple sites likely lacks centralized ops software']::text[], 'Multi-site community network needs centralized enrollment/tuition backbone across locations', 4, 'Medium', false, 'arizona', 'not_contacted', '', 'microadmin@blackmothersforums.com', '(602) 299-7630'),
  ('citrus-grove-microschool', 'Citrus Grove Microschool', 'AZ', 'Maricopa', 'https://citrusgrovemicroschool.com', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established local single-site program']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Small single-site program is a low-friction SaaS adoption candidate', 3, 'Medium', false, 'arizona', 'not_contacted', '', '', '(435) 881-8552'),
  ('copper-sky-academy', 'Copper Sky Academy', 'AZ', 'Scottsdale', '', 'Microschool', 'Not specified', 'Small', '$0 (per directory)', ARRAY['National Microschooling Center member']::text[], ARRAY['Minimal public web presence, no tuition transparency']::text[], 'Needs foundational website, transparent tuition display, and enrollment tooling', 3, 'Low', false, 'arizona', 'not_contacted', '', 'info@copperskyacademy.com', '(480) 978-0006'),
  ('desert-dragon-school', 'Desert Dragon School', 'AZ', 'Tucson', 'https://desertdragonlearning.com', 'Project-Based (learning differences)', '6-8', 'Small', 'Not published', ARRAY['Specializes in learning differences, personalized project-based autonomy']::text[], ARRAY['Specialized needs tracking likely manual/paper-based']::text[], 'Learning-differences focus needs individualized progress/IEP-style tracking tools', 4, 'Medium', false, 'arizona', 'not_contacted', '', '', ''),
  ('faithscape-learning-pod', 'Faithscape Learning Pod', 'AZ', 'Casa Grande', 'https://faithscapelearning.com', 'Microschool (faith-based)', 'Not specified', 'Small', 'Not published', ARRAY['Faith-integrated pod model, niche community focus']::text[], ARRAY['Small faith pod likely lacks dedicated enrollment/billing software']::text[], 'Faith-based niche pod is a good vertical fit for FieldBook', 3, 'Medium', false, 'arizona', 'not_contacted', '', 'info@faithscapelearning.com', ''),
  ('freedom-prep-academy', 'Freedom Prep Academy', 'AZ', 'Valley-wide (multiple partner sites)', 'https://freedomk12.org', 'Microschool network (K-12)', 'K-12', 'Multiple partner sites', 'Not published', ARRAY['Valley-wide partner network model, broad K-12 reach']::text[], ARRAY['Multi-site partner network likely lacks unified cross-site ops platform']::text[], 'Partner-site network model needs centralized multi-location enrollment/tuition system', 4, 'Medium', false, 'arizona', 'not_contacted', '', '', '(480) 256-2642'),
  ('grace-place-learning-lab', 'Grace Place Learning Lab', 'AZ', 'Tempe', 'https://graceplacelearning.com', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site program with public contact info']::text[], ARRAY['Small single-site likely manual admin/enrollment']::text[], 'Low-friction SaaS adoption candidate with an active phone contact', 3, 'Medium', false, 'arizona', 'not_contacted', '', '', '(480) 863-6234'),
  ('launchkids-academy', 'LaunchKids Academy', 'AZ', 'Phoenix & Scottsdale', 'https://launchkidsacademy.com', 'Microschool', 'Not specified', 'Small (2 sites)', 'Not published', ARRAY['Multi-site presence across Phoenix/Scottsdale']::text[], ARRAY['Two-site operation likely needs unified backend']::text[], 'Multi-site model is a strong upsell case for centralized ops', 4, 'Medium', false, 'arizona', 'not_contacted', '', 'hello@launchkidscollective.com', ''),
  ('innovators-learning-lab', 'Innovators Learning Lab', 'AZ', 'Phoenix', 'https://innovatorslearninglab.org', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established brand with public contact, innovation-focused positioning']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Low-friction SaaS adoption candidate with active phone/email contact', 3, 'Medium', false, 'arizona', 'not_contacted', '', 'info@innovatorslearninglab.org', '(602) 812-6603'),
  ('inspire-academy-of-schools', 'Inspire Academy of Schools', 'AZ', 'Sun City', 'https://inspireacademyofschools.com', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Serves a retirement-community-adjacent market niche']::text[], ARRAY['Small niche market school likely manual admin']::text[], 'Niche market school benefits from affordable all-in-one SaaS', 3, 'Medium', false, 'arizona', 'not_contacted', '', '', '(909) 346-3246'),
  ('kaipod-learning-gilbert-scottsdale-surprise', 'Kaipod Learning (Gilbert, Scottsdale, Surprise)', 'AZ', 'Gilbert / Scottsdale / Surprise', 'https://kaipodlearning.com', 'Hybrid Academy (multi-site)', 'Not specified', 'Multiple sites', 'Not published', ARRAY['Multi-site hybrid model, established brand across 3 AZ locations']::text[], ARRAY['Multi-site hybrid scheduling (in-person + remote) is operationally complex']::text[], 'Multi-site hybrid network is a strong upsell case for FieldBook''s scheduling and cross-site tools', 4, 'Medium', false, 'arizona', 'not_contacted', '', '', ''),
  ('live-to-learn-microschool', 'Live to Learn Microschool', 'AZ', 'Arizona (statewide)', 'https://livetolearnmicroschool.com', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established brand name, statewide reach']::text[], ARRAY['Limited public detail on operations']::text[], 'Needs foundational digital presence and enrollment tooling', 3, 'Low', false, 'arizona', 'not_contacted', '', '', ''),
  ('moreana-boys-academy', 'Moreana Boys Academy', 'AZ', 'Gilbert', 'https://moreana-az.com', 'Microschool (single-gender)', 'Not specified', 'Small', 'Not published', ARRAY['Single-gender focus, niche positioning']::text[], ARRAY['Niche single-gender program likely manual admin']::text[], 'Niche single-gender school is a good vertical fit for tailored SaaS onboarding', 3, 'Medium', false, 'arizona', 'not_contacted', '', 'tdowell@moreana-az.com', '(480) 431-8410'),
  ('neurocatalyst-academy', 'NeuroCatalyst Academy', 'AZ', 'Mesa', 'https://neurocatalystacademy.org', 'Microschool (neurodivergent focus)', 'Not specified', 'Small', 'Not published', ARRAY['Specializes in neurodivergent learners, individualized approach']::text[], ARRAY['Specialized needs tracking likely manual/paper-based']::text[], 'Neurodivergent-focused school needs individualized progress/IEP-style tracking', 4, 'Medium', false, 'arizona', 'not_contacted', '', 'Neurocatalystacademy@gmail.com', '(480) 504-1816'),
  ('new-gains-academy', 'New Gains Academy', 'AZ', 'Glendale', 'https://newgainsacademy.com', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site program with public contact']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Low-friction SaaS adoption candidate with active phone/email contact', 3, 'Medium', false, 'arizona', 'not_contacted', '', 'teachers@newgainsacademy.com', '(602) 341-3240'),
  ('paradigm-learning', 'Paradigm Learning', 'AZ', 'Gilbert', 'https://paradigm-learning.com', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site program with named contact']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Named contact makes this a good direct-outreach target', 3, 'Medium', false, 'arizona', 'not_contacted', 'Jody Cordova', 'jodycordova@paradigm-learning.com', '(602) 804-3393'),
  ('primer-microschool-scottsdale', 'Primer Microschool - Scottsdale', 'AZ', 'Scottsdale', 'https://primer.com', 'Microschool (Primer network)', 'Not specified', 'Small', '$0 (per directory)', ARRAY['Backed by Primer''s national microschool network/tech platform']::text[], ARRAY['Network already provides guide-level tools; harder sell at school level']::text[], 'Primer network schools may already have proprietary tools — lower priority, but tuition/enrollment gaps may remain', 2, 'Low', false, 'arizona', 'not_contacted', '', '', ''),
  ('rethink-microschool', 'ReThink Microschool', 'AZ', 'Gilbert', 'https://rethinkmicroschools.org', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site program with public contact info']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Low-friction SaaS adoption candidate with active phone/email contact', 3, 'Medium', false, 'arizona', 'not_contacted', '', 'info@rethinkmicroschools.org', '(602) 892-0099'),
  ('roots-and-wings-microschool', 'Roots and Wings Microschool', 'AZ', 'North Mesa', 'https://rootsandwingsmicroschool.com', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Nature-themed branding suggests outdoor/growth-oriented philosophy']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Nature-themed branding overlaps with Sage Field''s outdoor philosophy', 4, 'Low', false, 'arizona', 'not_contacted', '', '', ''),
  ('sequoia-choice', 'Sequoia Choice', 'AZ', 'Mesa', 'https://sequoiachoice.org', 'Microschool/charter-adjacent', 'Not specified', 'Medium-Large (network)', 'Not published', ARRAY['Larger network scale, established brand']::text[], ARRAY['Larger scale may already have district-grade SIS, reducing fit']::text[], 'Larger network likely has existing SIS — lower priority unless targeting a specific small site', 2, 'Low', false, 'arizona', 'not_contacted', '', '', '(480) 461-3222'),
  ('serenity-in-chaos-education', 'Serenity in Chaos Education', 'AZ', 'Mesa', 'https://siceeducation.com', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site program with named contact']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Named contact makes this a good direct-outreach target', 3, 'Medium', false, 'arizona', 'not_contacted', 'Lisha', 'lisha@siceducation.com', ''),
  ('sonoran-learning-collective', 'Sonoran Learning Collective', 'AZ', 'Cave Creek', 'https://sonoranlearningcollective.org', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site program with public contact']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Low-friction SaaS adoption candidate with active phone/email contact', 3, 'Medium', false, 'arizona', 'not_contacted', '', 'info@sonoranlearningcollective.org', '(480) 447-4676'),
  ('suewong-mcfadden-academy', 'Suewong McFadden Academy', 'AZ', 'Avondale', 'https://thesmacademy.org', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site program with named contact']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Named contact makes this a good direct-outreach target', 3, 'Medium', false, 'arizona', 'not_contacted', '', 'info@thesmacademy.org', '(919) 884-7315'),
  ('the-marvelous-microschool', 'The Marvelous Microschool', 'AZ', 'Kingman', 'https://themarvelousmicroschool.com', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Rural NW Arizona presence, underserved market']::text[], ARRAY['Rural market likely lean staff, manual admin']::text[], 'Rural lean-team school is a strong candidate for affordable all-in-one SaaS', 4, 'Medium', false, 'arizona', 'not_contacted', '', 'themarvelousmicroschool@gmail.com', '(928) 488-1759'),
  ('the-modern-schoolhouse-microschool', 'The Modern Schoolhouse Microschool', 'AZ', 'Phoenix', 'https://themodernschoolhouse.org', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site program with public contact']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Low-friction SaaS adoption candidate with active phone/email contact', 3, 'Medium', false, 'arizona', 'not_contacted', '', 'admin@themodernschoolhouse.org', '(623) 287-9024'),
  ('trinity-arch-preparatory-school-for-boys', 'Trinity Arch Preparatory School for Boys', 'AZ', 'Phoenix', 'https://trinityarchprep.com', 'Microschool (single-gender, faith-based)', 'Not specified', 'Small', 'Not published', ARRAY['Single-gender, faith-based niche positioning']::text[], ARRAY['Niche program likely manual admin']::text[], 'Faith-based single-gender niche school is a good vertical fit for tailored SaaS onboarding', 3, 'Low', false, 'arizona', 'not_contacted', '', '', '(602) 299-9079'),
  ('true-north-academy', 'True North Academy', 'AZ', 'Scottsdale', 'https://truenorthaz.org', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site program with named admissions contact']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Active admissions contact makes this a good direct-outreach target', 3, 'Medium', false, 'arizona', 'not_contacted', '', 'admissions@truenorthaz.org', ''),
  ('waybright-academy', 'Waybright Academy', 'AZ', 'Scottsdale', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['National Microschooling Center member']::text[], ARRAY['Minimal public web presence found']::text[], 'Needs foundational website + enrollment system', 3, 'Low', false, 'arizona', 'not_contacted', '', '', ''),
  ('wicket-academy', 'Wicket Academy', 'AZ', 'Mesa', 'https://wicketacademy.org', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['Established single-site program']::text[], ARRAY['Small single-site likely manual admin']::text[], 'Low-friction SaaS adoption candidate', 3, 'Low', false, 'arizona', 'not_contacted', '', '', ''),
  ('a-mind-of-magic-and-reason-learning-center', 'A Mind of Magic and Reason Learning Center', 'AZ', 'Tucson', 'https://amindofmagicandreason.com', 'Project-Based', 'K-8', 'Small', 'Not published', ARRAY['Curiosity-driven, hands-on personalized learning pathways']::text[], ARRAY['Wide K-8 span with individualized paths likely tracked manually']::text[], 'Individualized pathway tracking is a strong fit for FieldBook''s flexible progress tools', 4, 'Medium', false, 'arizona', 'not_contacted', '', '', ''),
  ('coy-s-camps-and-classes-prodigypreneurs', 'Coy''s Camps And Classes: Prodigypreneurs', 'AZ', 'Tucson', '', 'Project-Based (entrepreneurship)', 'K-8', 'Small', 'Not published', ARRAY['Hybrid flexible schedule, entrepreneurship/STEAM electives, self-directed goal-setting']::text[], ARRAY['Hybrid + elective structure likely complex to schedule manually']::text[], 'Hybrid schedule + elective structure is a strong fit for FieldBook''s flexible scheduling engine', 4, 'Low', false, 'arizona', 'not_contacted', '', '', ''),
  ('mrs-arienne-s-microschool', 'Mrs. Arienne''s Microschool', 'AZ', 'Tucson', '', 'Microschool (Prenda network)', '1-6', 'Small', 'Not published', ARRAY['Prenda-powered, personalized small-group instruction']::text[], ARRAY['Prenda tools may not cover full school-level ops (tuition, site, apps)']::text[], 'Prenda-affiliated school could still need dedicated site/tuition/app management', 3, 'Low', false, 'arizona', 'not_contacted', '', '', ''),
  ('tucson-international-academy', 'Tucson International Academy', 'AZ', 'Tucson', '', 'Microschool', 'Not specified', 'Small', 'Not published', ARRAY['National Microschooling Center member']::text[], ARRAY['Minimal public web presence found']::text[], 'Needs foundational website + enrollment system', 3, 'Low', false, 'arizona', 'not_contacted', '', '', ''),
  ('april-simmons-microschool-sazmc-member', 'April Simmons'' Microschool (SAZMC member)', 'AZ', 'Tucson', 'https://www.sazmicroschoolcollective.org', 'Microschool', '3-8', 'Small', 'Not published', ARRAY['Member of Southern Arizona Microschool Collective, Mon-Thu schedule structure']::text[], ARRAY['Alt-schedule (4-day week) programs likely need custom calendar tools']::text[], 'Alt-schedule model needs flexible calendar/billing tools tailored to non-standard weeks', 4, 'Medium', false, 'arizona', 'not_contacted', 'April Simmons', '', '(520) 789-8368'),
  ('desert-dragon-learning-community', 'Desert Dragon Learning Community', 'AZ', 'Tucson', 'https://desertdragonlearning.com', 'Microschool (learning differences)', '5-12', 'Small', 'Not published', ARRAY['Small learning space for neurodivergent students with learning differences']::text[], ARRAY['Wide 5-12 span with individualized needs likely manual tracking']::text[], 'Neurodivergent-focused wide-span school needs individualized progress/IEP-style tracking', 4, 'Medium', false, 'arizona', 'not_contacted', '', '', ''),
  ('exploratory-personalized-education-sazmc-member', 'Exploratory Personalized Education (SAZMC member)', 'AZ', 'Tucson', 'https://www.sazmicroschoolcollective.org', 'Microschool', 'K-12', 'Small', 'Not published', ARRAY['Personalized exploratory education model, full K-12 span']::text[], ARRAY['Full K-12 span in one small program strains manual admin']::text[], 'Full K-12 span in a small program is ideal for FieldBook''s grade/tuition management', 4, 'Low', false, 'arizona', 'not_contacted', '', '', ''),
  ('open-minds-homesteading-microschool', 'Open Minds (Homesteading Microschool)', 'AZ', 'Tucson', 'https://www.sazmicroschoolcollective.org', 'Microschool (homesteading/nature)', 'K-8 (split K-4 / 5-8 groups)', 'Small', 'Not published', ARRAY['Homesteading-focused, nature-based curriculum — strong overlap with Sage Field''s outdoor model']::text[], ARRAY['Split-group scheduling (K-4 / 5-8) likely managed manually']::text[], 'Direct outdoor/homesteading philosophical match — ideal MudKitchen prospect', 5, 'Medium', false, 'arizona', 'not_contacted', '', '', ''),
  ('k-12-prenda-model-microschool-sazmc-member-oracle-river-rd', 'K-12 Prenda-Model Microschool (SAZMC member, Oracle/River Rd)', 'AZ', 'Tucson', 'https://www.sazmicroschoolcollective.org', 'Microschool (Prenda-model, home-based)', 'K-12', 'Small', 'Not published', ARRAY['Home-based Prenda-model program, full K-12 span']::text[], ARRAY['Home-based single-operator program likely entirely manual']::text[], 'Home-based single-operator school is a prime low-friction adoption target', 4, 'Medium', false, 'arizona', 'not_contacted', '', '', '')

on conflict (school_id) do nothing;

-- Verification (run after import)
-- Expect 51 rows for the imported Arizona batch.
select count(*) as arizona_import_count
from public.schools
where source_file = 'arizona'
  and school_id in (
    'acton-academy-east-valley',
    'off-trail-adventures-santan-shredders',
    'the-learning-vine',
    'ato-academy',
    'gifted-microschool-at-the-gifted-collective',
    'peak-learning-academy',
    'sunshine-learning-academy',
    'the-h-e-a-r-t-center',
    'vita-high-school',
    'kat-s-community-microschool',
    'aloha-micro-academy',
    'anchor-microschools',
    'az-steam-academy',
    'bmf-microschools',
    'citrus-grove-microschool',
    'copper-sky-academy',
    'desert-dragon-school',
    'faithscape-learning-pod',
    'freedom-prep-academy',
    'grace-place-learning-lab',
    'launchkids-academy',
    'innovators-learning-lab',
    'inspire-academy-of-schools',
    'kaipod-learning-gilbert-scottsdale-surprise',
    'live-to-learn-microschool',
    'moreana-boys-academy',
    'neurocatalyst-academy',
    'new-gains-academy',
    'paradigm-learning',
    'primer-microschool-scottsdale',
    'rethink-microschool',
    'roots-and-wings-microschool',
    'sequoia-choice',
    'serenity-in-chaos-education',
    'sonoran-learning-collective',
    'suewong-mcfadden-academy',
    'the-marvelous-microschool',
    'the-modern-schoolhouse-microschool',
    'trinity-arch-preparatory-school-for-boys',
    'true-north-academy',
    'waybright-academy',
    'wicket-academy',
    'a-mind-of-magic-and-reason-learning-center',
    'coy-s-camps-and-classes-prodigypreneurs',
    'mrs-arienne-s-microschool',
    'tucson-international-academy',
    'april-simmons-microschool-sazmc-member',
    'desert-dragon-learning-community',
    'exploratory-personalized-education-sazmc-member',
    'open-minds-homesteading-microschool',
    'k-12-prenda-model-microschool-sazmc-member-oracle-river-rd'
  );

-- Confirm skipped duplicate still exists (should return 1 row)
select school_id, name
from public.schools
where school_id = 'desert-sun-ranch-academy';

